### ISSUE TITLE
Not so much an issue, as a question

### ISSUE THREAD

**Issue by wabala94** [1Konny/gradcam_plus_plus-pytorch#1]
Hi! Thanks for your amazing work here. You've really made testing out gradcam a breeze. 

I have a question regarding the usage of these modules. When I create a saliency map using a model I have fine-tuned as the architecture, are the resulting maps shown for the original torchvision pretrained network or my fine-tuned model?

Thanks in advance.

```python

# model is fine-tuned on task-specific classification, initialized with pretrained resnet18 torchvision model weights

model.eval()
resnet_model_dict = dict(type='resnet', arch=model, layer_name='layer4',
                        input_size=(224,224))

resnet_gradcam = GradCAM(resnet_model_dict, True)
resnet_gradcampp = GradCAMpp(resnet_model_dict, True)

```

**Comment by 1Konny** [comment]
Hi.

GradCAM module will generate heatmaps using the model initialized by your fine-tuned network parameters, not by ones from torchvision.

**Comment by wabala94** [comment]
Ok, that's perfect - just wanted to make sure I was understanding its usage correctly.  Thanks!
